### PR TITLE
Ignore IBAN numbers.

### PR DESCRIPTION
**Pull request by bierik**
Closes
https://extranet.4teamwork.ch/support/stadt-winterthur/tracker-web/54

### CODE REVIEW

**Comment by jone** [comment]
If I understand the issue correctly, only the first few digits of the IBAN matches as phone number. Although blacklisting IBANs would solve this case, couldn't we find a more general solution?

I think if we can avoid that we match a substring but try to match the complete number sequence we would realize that we have too many digits and could stop matching it, right?
So we could change the regex to make a look-ahead and not match when more numbers follow and we have therefore an unexpected length.

If this would work we could fix other cases too, where we probably will match the starting sequence of longer number sequences as false positives.

**Comment by bierik** [comment]
Instead of introducing an even more complex regex I am more tending to try https://github.com/4teamwork/ftw.candlestick/issues/13. This way you have a pipeline with trivial sub filters. This way each part of the pipeline could be tested independently.

**Comment by jone** [comment]
https://www.regular-expressions.info/lookaround.html

**Comment by bierik** [comment]
@jone updated

**Pull request merged**
